name: deploy-landing-zone
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      instanceName:
        description: 'Instance Name'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure Commands
      uses: azure/CLI@v1
      env:
        INSTANCE_NAME: ${{ github.event.inputs.instanceName }}
        RESOURCE_GROUP_NAME: ${{ env.INSTANCE_NAME }}-terraform-backend
        CONTAINER_NAME: tfstate
        STORAGE_ACCOUNT_NAME: ${{ env.INSTANCE_NAME }}
      with:
        azcliversion: 2.33.1
        inlineScript: |
          # Create resource group
          az group create --name $RESOURCE_GROUP_NAME --location eastus
