name: deploy-landing-zone
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: Azure/login@v1.4.6
      with:
        client-id: "3faf8d5c-78a2-444a-bea2-be436037973b"
        tenant-id: "8bcff170-9979-491e-8683-d8ced0850bad"
