name: test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input1'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a multi-line script
        env: 
          ENV1: "Env1"
          ENV2: "Env2"
          ENV3: ${{ env.ENV1 }}-${{ env.ENV2 }}
        run: |
          echo Add other actions to build,
          echo env1: $ENV1
          echo env2: $ENV2
          echo env3: $ENV3
      
