# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.33.1
          inlineScript: |
            # Set Environment Variables using the generated credentials
            export ARM_TENANT_ID="8bcff170-9979-491e-8683-d8ced0850bad"
            export ARM_CLIENT_ID="3faf8d5c-78a2-444a-bea2-be436037973b"
            export ARM_CLIENT_SECRET="FHQ8Q~vZPTuliVAQRSnZrJhKYBZ-qcuugdxcyafU"
            export ARM_SUBSCRIPTION_ID="0212baad-e8a6-41d3-8d3d-75050f31bf1f"

            # Test Credentials
            az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
