name: test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v2
      
    - name: Create Backend Conf File for Terraform
      run: |
        # Create Terraform Conf File
        cat << EOF > backend.conf
        resource_group_name   = "hlasalesdemok231-terraform-backend"
        storage_account_name  = "hlasalesdemok231"
        container_name        = "tfstate"
        EOF
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0

    - name: Terraform Plan
      run: |
        # Terraform  Plan
        export ARM_TENANT_ID="8bcff170-9979-491e-8683-d8ced0850bad"
        export ARM_CLIENT_ID="3faf8d5c-78a2-444a-bea2-be436037973b"
        export ARM_CLIENT_SECRET="FHQ8Q~vZPTuliVAQRSnZrJhKYBZ-qcuugdxcyafU"
        export ARM_SUBSCRIPTION_ID="0212baad-e8a6-41d3-8d3d-75050f31bf1f"
        # export ARM_ACCESS_KEY="hON8MaJiCHSY+VUng+p37PT15j1EdA5/cuqsiHBGlgp5AHqLxqcMgUp9LXCeCxg1aP5Y7Zfw/Aqt+AStlYoBnQ=="
        az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID   
        terraform init -backend-config=backend.conf
        terraform plan -var instance_name=hlasalesdemok231
